
const allQuests = [
  // Nature & Outdoor
  {
    id: "trash-bag-hill-slide",
    title: "Trash Bag Toboggan",
    emoji: "🌧️",
    category: ["Nature", "Rainy Day", "Random"],
    difficulty: 2,
    duration: "20 minutes",
    description:
      "Find a grassy hill, grab a sturdy trash bag, and slide down it in the rain like you're twelve again.",
    objectives: [
      "Find a gentle grassy slope, not a rocky one",
      "Get a thick trash bag",
      "Slide down at least three times",
    ],
    tip: "Check the slope for rocks or roots before you go.",
    reward: "The kind of laugh you forgot you still had.",
    pack: "nature-outdoor",
  },
  {
    id: "go-on-a-hike",
    title: "Take the Long Way Up",
    emoji: "🥾",
    category: ["Nature", "Adventure", "Outdoor"],
    difficulty: 3,
    duration: "2-4 hours",
    description:
      "Pick a trail you've never walked and go the whole way, no matter how it starts.",
    objectives: [
      "Choose a trail new to you",
      "Bring water",
      "Reach the endpoint or turnaround",
    ],
    reward: "Legs that ache in a good way.",
    pack: "nature-outdoor",
  },
  {
    id: "camp-a-full-night",
    title: "One Night Under Canvas",
    emoji: "⛺",
    category: ["Nature", "Adventure", "Night"],
    difficulty: 3,
    duration: "Overnight",
    description:
      "Camp a full night in a forest or someone's backyard — sleep somewhere the ceiling isn't a ceiling.",
    objectives: [
      "Set up a tent or shelter",
      "Stay until morning",
      "No sneaking back inside at midnight",
    ],
    reward: "A story that starts with 'so we were sleeping outside...'",
    pack: "nature-outdoor",
  },
  {
    id: "climb-a-tree",
    title: "Become Unreachable",
    emoji: "🌲",
    category: ["Nature", "Adventure"],
    difficulty: 2,
    duration: "30 minutes",
    description:
      "Find a tree you've never climbed. Get up there. Stay a while.",
    objectives: [
      "Find a sturdy climbable tree",
      "Get at least a few branches up",
      "Stay for ten minutes",
    ],
    reward: "A view nobody at ground level gets.",
    pack: "nature-outdoor",
  },
  {
    id: "fire-and-smores",
    title: "Fire and S'mores",
    emoji: "🔥",
    category: ["Nature", "Friends", "Night"],
    difficulty: 2,
    duration: "1-2 hours",
    description:
      "Build a proper fire, then make s'mores over it like that's a completely normal Tuesday.",
    objectives: [
      "Build the fire safely",
      "Toast a marshmallow without torching it",
      "Eat at least two s'mores",
    ],
    reward: "Smoke in your clothes for two days, worth it.",
    pack: "nature-outdoor",
  },
  {
    id: "find-a-swimming-spot",
    title: "The Local Swimming Hole",
    emoji: "🏊",
    category: ["Nature", "Adventure", "Friends"],
    difficulty: 2,
    duration: "2 hours",
    description:
      "Find a swimming spot nearby you've never used and spend an afternoon there.",
    objectives: [
      "Find a safe, known swimming spot",
      "Actually get in the water",
      "Stay a couple hours",
    ],
    reward: "Sun-dried hair and a new favorite spot.",
    pack: "nature-outdoor",
  },
  {
    id: "float-down-a-river",
    title: "Drift Downstream",
    emoji: "🛶",
    category: ["Nature", "Adventure", "Friends"],
    difficulty: 3,
    duration: "2-3 hours",
    description:
      "Get life jackets and float down a calm stretch of river with no particular plan.",
    objectives: [
      "Get proper life jackets for everyone",
      "Choose a calm, known stretch of river",
      "Float until you're ready to stop",
    ],
    tip: "Keep the life jacket on the whole time, even in calm water.",
    reward: "The specific peace of moving without paddling.",
    pack: "nature-outdoor",
  },
  {
    id: "sleep-under-the-stars",
    title: "No Roof Tonight",
    emoji: "✨",
    category: ["Nature", "Night", "Solo"],
    difficulty: 3,
    duration: "Overnight",
    description: "Sleep somewhere you've never been, under nothing but sky.",
    objectives: [
      "Pick a new, safe location",
      "Sleep without a tent if weather allows",
      "Wake up with the sun",
    ],
    reward: "A ceiling made of stars, for one night only.",
    pack: "nature-outdoor",
  },
  {
    id: "highest-point-sunset",
    title: "The View From Up Here",
    emoji: "🌇",
    category: ["Nature", "Solo", "Photography"],
    difficulty: 2,
    duration: "1 hour",
    description:
      "Find the highest point in your city and watch the sunset from there.",
    objectives: [
      "Find your city's highest accessible point",
      "Arrive before sunset",
      "Watch it fully, no scrolling",
    ],
    reward: "Your whole city, lit orange, just for you.",
    pack: "nature-outdoor",
  },
  {
    id: "learn-constellations",
    title: "Name the Sky",
    emoji: "🌌",
    category: ["Nature", "Night", "Solo"],
    difficulty: 2,
    duration: "1 hour",
    description:
      "Learn 10 constellations, then go outside and actually find them.",
    objectives: [
      "Learn 10 constellations",
      "Find a dark enough spot",
      "Spot at least 5 of them for real",
    ],
    reward: "The sky stops being random dots.",
    pack: "nature-outdoor",
  },
  {
    id: "watch-sunrise-fully",
    title: "The Whole Sunrise",
    emoji: "🌅",
    category: ["Nature", "Solo"],
    difficulty: 2,
    duration: "45 minutes",
    description:
      "Wake up early and watch the entire sunrise without checking your phone once.",
    objectives: [
      "Get there before the sky starts changing",
      "Phone stays away",
      "Watch until it's fully light",
    ],
    reward: "A version of morning you usually sleep through.",
    pack: "nature-outdoor",
  },
  {
    id: "balcony-garden",
    title: "Something Green of Your Own",
    emoji: "🌱",
    category: ["Nature", "Creativity", "Indoor"],
    difficulty: 1,
    duration: "1 hour",
    description:
      "Start a small balcony or windowsill garden — even one pot counts.",
    objectives: [
      "Get a pot and soil",
      "Plant something",
      "Give it a name if you want",
    ],
    reward: "A living thing that depends on you now.",
    pack: "nature-outdoor",
  },
  {
    id: "new-place-in-own-city",
    title: "The Part You've Never Seen",
    emoji: "🧭",
    category: ["Nature", "Adventure", "Solo"],
    difficulty: 1,
    duration: "2 hours",
    description: "Go somewhere in your own city you've genuinely never been.",
    objectives: [
      "Pick a spot you've never visited",
      "Actually go",
      "Notice three things you didn't expect",
    ],
    reward: "Proof your own city still has secrets.",
    pack: "nature-outdoor",
  },

  // Connection
  {
    id: "cafe-stranger-conversation",
    title: "Talk to Someone New",
    emoji: "☕",
    category: ["Friends", "Solo"],
    difficulty: 3,
    duration: "30 minutes",
    description:
      "Strike up a real conversation with a stranger at a café — and actually listen.",
    objectives: [
      "Start the conversation",
      "Ask a real question",
      "Actually listen to the answer",
    ],
    reward: "A five-minute glimpse into a whole other life.",
    pack: "connection",
  },
  {
    id: "letter-to-someone-who-changed-you",
    title: "The Letter You Never Sent",
    emoji: "✉️",
    category: ["Friends", "Solo"],
    difficulty: 3,
    duration: "45 minutes",
    description:
      "Write a letter to someone who changed your life. Then actually send it.",
    objectives: [
      "Write it honestly",
      "Don't overthink the ending",
      "Send it — mail or hand it over",
    ],
    reward: "Something they'll probably keep forever.",
    pack: "connection",
  },
  {
    id: "attend-alone",
    title: "Show Up Solo",
    emoji: "🎭",
    category: ["Friends", "Solo", "Adventure"],
    difficulty: 3,
    duration: "2-3 hours",
    description: "Attend an event where you know absolutely no one.",
    objectives: [
      "Pick an event",
      "Go alone",
      "Talk to at least one new person there",
    ],
    reward: "Proof you don't need a plus-one to have a good time.",
    pack: "connection",
  },
  {
    id: "compliment-five-strangers",
    title: "Five Honest Compliments",
    emoji: "💬",
    category: ["Friends"],
    difficulty: 2,
    duration: "1 day",
    description: "Compliment five strangers today, and mean every word.",
    objectives: [
      "Give 5 genuine compliments",
      "No generic lines — mean it each time",
    ],
    reward: "Five small moments you made better.",
    pack: "connection",
  },
  {
    id: "call-old-friend",
    title: "No Agenda, Just a Call",
    emoji: "📞",
    category: ["Friends"],
    difficulty: 1,
    duration: "20 minutes",
    description:
      "Call an old friend you haven't spoken to in years, just to talk. No agenda.",
    objectives: [
      "Actually call, don't text first",
      "No reason needed",
      "Just catch up",
    ],
    reward: "Proof some things pick back up like no time passed.",
    pack: "connection",
  },
  {
    id: "cook-for-someone-in-need",
    title: "A Meal for Someone Who Needs It",
    emoji: "🍲",
    category: ["Friends", "Food"],
    difficulty: 2,
    duration: "1-2 hours",
    description:
      "Cook a full meal for someone who genuinely needs it right now.",
    objectives: [
      "Find someone who could use a meal",
      "Cook it properly",
      "Deliver it yourself",
    ],
    reward: "Full stomachs, on both ends.",
    pack: "connection",
  },
  {
    id: "ask-an-elder-about-regret",
    title: "A Lifetime in One Answer",
    emoji: "🧓",
    category: ["Friends", "Growth", "Solo"],
    difficulty: 2,
    duration: "30-60 minutes",
    description:
      "Ask an older person what their biggest regret is, then give them something increasingly rare: your full attention.",
    objectives: [
      "Ask them about their biggest regret",
      "Listen without interrupting",
      "Keep your phone away the entire conversation",
    ],
    reward: "A lesson someone spent decades learning.",
    pack: "connection",
  },
  {
    id: "volunteer-anonymously",
    title: "Do Good, Stay Unknown",
    emoji: "🤝",
    category: ["Friends", "Growth"],
    difficulty: 2,
    duration: "2-4 hours",
    description:
      "Spend time helping others without telling anyone afterward. Let the good deed exist without an audience.",
    objectives: [
      "Find a place or person to help",
      "Volunteer your time or skills",
      "Tell no one about it afterward",
    ],
    reward: "The quiet satisfaction of doing the right thing anyway.",
    pack: "connection",
  },

  // Solo
  {
    id: "fancy-restaurant-alone",
    title: "Table for One",
    emoji: "🍷",
    category: ["Solo", "Food"],
    difficulty: 3,
    duration: "2 hours",
    description:
      "Take yourself somewhere nice to eat and enjoy your own company like it's the reservation you were hoping for.",
    objectives: [
      "Choose a restaurant you've wanted to try",
      "Order exactly what you want",
      "Stay off your phone during the meal",
    ],
    reward: "Proof your own company is enough.",
    pack: "solo",
  },
  {
    id: "third-person-journal",
    title: "The Story of You",
    emoji: "📖",
    category: ["Solo", "Creativity"],
    difficulty: 2,
    duration: "30 minutes",
    description:
      "Write about your day as if you're the main character in a novel and the narrator knows you better than you do.",
    objectives: [
      "Write at least one full page",
      "Use only third person",
      "Include one honest observation about yourself",
    ],
    reward: "A new perspective on an ordinary day.",
    pack: "solo",
  },
  {
    id: "record-yourself-speaking",
    title: "Meet Your Own Voice",
    emoji: "🎙️",
    category: ["Solo", "Growth"],
    difficulty: 2,
    duration: "20 minutes",
    description:
      "Record yourself talking freely for ten minutes, then listen back without judging every little detail.",
    objectives: [
      "Talk continuously for ten minutes",
      "Play the recording back",
      "Write down one thing you learned",
    ],
    reward: "A version of yourself you rarely hear.",
    pack: "solo",
  },
  {
    id: "solo-breakfast-date",
    title: "Breakfast for One",
    emoji: "🥐",
    category: ["Solo", "Food"],
    difficulty: 2,
    duration: "1-2 hours",
    description:
      "Wake up early and treat yourself to breakfast somewhere you've never been before.",
    objectives: [
      "Choose a new café or bakery",
      "Eat without rushing",
      "Notice three things about the place",
    ],
    reward: "A slower morning than usual.",
    pack: "solo",
  },
  {
    id: "day-without-phone",
    title: "Offline for a While",
    emoji: "📵",
    category: ["Solo", "Growth"],
    difficulty: 4,
    duration: "1 day",
    description:
      "Spend an entire day without your phone and discover how much time quietly comes back to you.",
    objectives: [
      "Turn your phone off or leave it behind",
      "Avoid all social media",
      "Fill the day with real-world activities",
    ],
    reward: "A day that actually felt like a day.",
    pack: "solo",
  },
  {
    id: "silent-day",
    title: "The Quiet Experiment",
    emoji: "🤫",
    category: ["Solo", "Growth"],
    difficulty: 4,
    duration: "1 day",
    description:
      "Speak only when absolutely necessary and let silence do more of the work than words.",
    objectives: [
      "Avoid unnecessary conversations",
      "Communicate simply when needed",
      "Reflect on how the day felt afterward",
    ],
    reward: "A mind that's a little less noisy.",
    pack: "solo",
  },
  {
    id: "cook-three-course-meal",
    title: "Dinner Worth Dressing Up For",
    emoji: "🍽️",
    category: ["Solo", "Food", "Creativity"],
    difficulty: 3,
    duration: "2-3 hours",
    description:
      "Cook yourself a full three-course meal, set the table properly, and enjoy every course without rushing.",
    objectives: [
      "Prepare a starter, main, and dessert",
      "Set the table nicely",
      "Eat without distractions",
    ],
    reward: "A reminder that you're worth the effort too.",
    pack: "solo",
  },
  {
    id: "plan-your-ideal-life",
    title: "No Limits on Paper",
    emoji: "🗺️",
    category: ["Solo", "Growth"],
    difficulty: 3,
    duration: "2 hours",
    description:
      "Design your ideal life in as much detail as you can, without worrying whether it seems realistic yet.",
    objectives: [
      "Write about where you'd live",
      "Describe your ideal work and relationships",
      "Finish with three steps you could start this year",
    ],
    reward: "A destination that's finally visible.",
    pack: "solo",
  },

  // Creativity
  {
    id: "thirty-photos-one-hour",
    title: "Thirty Frames",
    emoji: "📸",
    category: ["Creativity", "Photography", "Solo"],
    difficulty: 2,
    duration: "1 hour",
    description:
      "Take thirty photos in one hour without filters or second chances. Trust your first instinct and let the imperfect shots stay imperfect.",
    objectives: [
      "Take exactly 30 photos",
      "Don't use filters or editing",
      "Don't retake any photo",
    ],
    reward: "A reminder that moments don't ask for perfection.",
    pack: "creativity",
  },
  {
    id: "historical-life-story",
    title: "Two Hundred Years Earlier",
    emoji: "✍️",
    category: ["Creativity", "Writing", "Solo"],
    difficulty: 3,
    duration: "1-2 hours",
    description:
      "Write a short story about your own life as if you were born two centuries ago. Keep your personality, change the world around you.",
    objectives: [
      "Write at least 1,000 words",
      "Set the story 200 years in the past",
      "Make yourself the main character",
    ],
    reward: "A strange little window into another lifetime.",
    pack: "creativity",
  },
  {
    id: "terrible-art",
    title: "Hang It Anyway",
    emoji: "🎨",
    category: ["Creativity", "Solo"],
    difficulty: 1,
    duration: "1 hour",
    description:
      "Create something spectacularly imperfect, then display it proudly. The goal isn't talent. It's permission.",
    objectives: [
      "Draw or paint something",
      "Finish without starting over",
      "Hang it somewhere you'll see it",
    ],
    reward: "One less reason to fear making things.",
    pack: "creativity",
  },
  {
    id: "rearrange-living-space",
    title: "A Different Room",
    emoji: "🛋️",
    category: ["Creativity", "Home"],
    difficulty: 2,
    duration: "2-4 hours",
    description:
      "Rearrange your room or living space completely. Sometimes a fresh perspective starts with moving the furniture.",
    objectives: [
      "Move your main furniture",
      "Declutter while rearranging",
      "Leave the room feeling genuinely different",
    ],
    reward: "The feeling of living somewhere new without moving.",
    pack: "creativity",
  },
  {
    id: "future-self-playlist",
    title: "Songs for Someone You'll Become",
    emoji: "🎧",
    category: ["Creativity", "Music", "Solo"],
    difficulty: 2,
    duration: "1 hour",
    description:
      "Build a playlist for a future version of yourself. Pick songs you hope they'll smile at when they finally press play.",
    objectives: [
      "Choose at least 20 songs",
      "Give the playlist a meaningful name",
      "Save it without listening all the way through",
    ],
    reward: "A time capsule made of music.",
    pack: "creativity",
  },
  {
    id: "declutter-one-hundred-items",
    title: "Make Room",
    emoji: "📦",
    category: ["Creativity", "Growth", "Home"],
    difficulty: 3,
    duration: "2-3 hours",
    description:
      "Find one hundred things you no longer need and let them go. Every object has a weight, even when it doesn't feel heavy.",
    objectives: [
      "Count 100 items",
      "Donate, recycle, or throw them away responsibly",
      "Leave the cleaned space organized",
    ],
    reward: "A room that finally has room to breathe.",
    pack: "creativity",
  },

  // City Explorer
  {
    id: "random-train-city",
    title: "Now Arriving Somewhere New",
    emoji: "🚆",
    category: ["Adventure", "Travel", "Solo"],
    difficulty: 4,
    duration: "Full day",
    description:
      "Buy a train ticket to a place you've never visited and figure out the day as you go. Leave space for surprise.",
    objectives: [
      "Choose a destination you've never explored",
      "Spend at least four hours there",
      "Discover one place that wasn't in your plan",
    ],
    tip: "Always keep a return ticket or a backup plan, just in case.",
    reward: "Confidence that grows with every unfamiliar street.",
    pack: "city-explorer",
  },
  {
    id: "tiny-town-visit",
    title: "The Small Dot on the Map",
    emoji: "🏘️",
    category: ["Adventure", "Travel"],
    difficulty: 3,
    duration: "Half day",
    description:
      "Visit a town with fewer than five hundred people and spend enough time to understand its slower rhythm.",
    objectives: [
      "Find a town under 500 residents",
      "Walk through the main area",
      "Talk to at least one local",
    ],
    reward: "Proof that interesting places don't need big populations.",
    pack: "city-explorer",
  },
  {
    id: "carry-on-flight",
    title: "Just Enough",
    emoji: "✈️",
    category: ["Adventure", "Travel"],
    difficulty: 5,
    duration: "2-3 days",
    description:
      "Take a flight carrying only the essentials and let the destination unfold before you instead of planning every minute.",
    objectives: [
      "Travel with only a carry-on bag",
      "Explore before deciding where to stay",
      "Adapt your plans as the day unfolds",
    ],
    tip: "Have a backup plan for the night sorted before you land.",
    reward: "The freedom that comes from needing less.",
    pack: "city-explorer",
  },
  {
    id: "hidden-museum",
    title: "Behind That Door",
    emoji: "🏛️",
    category: ["Adventure", "Culture"],
    difficulty: 2,
    duration: "2 hours",
    description:
      "Walk into a museum you've passed a hundred times but never entered. Curiosity deserves a chance now and then.",
    objectives: [
      "Visit a museum new to you",
      "Read about at least five exhibits",
      "Leave with one surprising fact",
    ],
    reward: "A story you almost walked past forever.",
    pack: "city-explorer",
  },
  {
    id: "explore-new-neighborhood",
    title: "The Street You Always Ignore",
    emoji: "🚶",
    category: ["Adventure", "Solo"],
    difficulty: 2,
    duration: "Full day",
    description:
      "Spend an entire day in a neighborhood you've only ever driven past. Walk slowly enough for it to become familiar.",
    objectives: [
      "Explore on foot",
      "Eat at a local café or restaurant",
      "Find one place worth returning to",
    ],
    reward: "Your city feels a little bigger than yesterday.",
    pack: "city-explorer",
  },
  {
    id: "memorize-poem",
    title: "Words Worth Keeping",
    emoji: "📜",
    category: ["Growth", "Creativity", "Solo"],
    difficulty: 2,
    duration: "2-3 days",
    description:
      "Choose a poem or passage that moves you and carry it in your memory instead of your pocket.",
    objectives: [
      "Choose a meaningful poem or passage",
      "Memorize it completely",
      "Recite it without looking",
    ],
    reward: "Words that stay with you for years.",
    pack: "city-explorer",
  },

  // Growth & Challenge
  {
    id: "future-self-letter",
    title: "Open in 2027",
    emoji: "📬",
    category: ["Growth", "Solo"],
    difficulty: 1,
    duration: "45 minutes",
    description:
      "Write a letter to the version of yourself waiting in 2027. Tell them what you hope they never forget.",
    objectives: [
      "Write honestly",
      "Seal the letter",
      "Don't open it before 2027",
    ],
    reward: "A conversation across time.",
    pack: "growth-challenge",
  },
  {
    id: "thirty-day-hobby",
    title: "Keep Showing Up",
    emoji: "🎯",
    category: ["Growth"],
    difficulty: 4,
    duration: "30 days",
    description:
      "Choose a hobby you've always wanted to learn and show up every day for a month. Progress likes consistency more than talent.",
    objectives: [
      "Choose one hobby",
      "Practice every day for 30 days",
      "Don't skip a single day",
    ],
    reward: "Thirty days of becoming someone slightly different.",
    pack: "growth-challenge",
  },
  {
    id: "different-route-home",
    title: "Another Way Home",
    emoji: "🛣️",
    category: ["Growth", "Adventure"],
    difficulty: 2,
    duration: "1 month",
    description:
      "Take a different route home every day for a month. Familiar places still have surprises if you stop repeating yourself.",
    objectives: [
      "Avoid your usual route",
      "Try a different path each day",
      "Notice something new every time",
    ],
    reward: "The ordinary becomes interesting again.",
    pack: "growth-challenge",
  },
  {
    id: "outside-comfort-book",
    title: "Someone Else's Shelf",
    emoji: "📚",
    category: ["Growth", "Solo"],
    difficulty: 2,
    duration: "1-2 weeks",
    description:
      "Read a book you'd normally never choose. Sometimes the stories we resist have the most to teach us.",
    objectives: [
      "Pick an unfamiliar genre",
      "Finish the book",
      "Write three things you learned",
    ],
    reward: "A slightly larger world than before.",
    pack: "growth-challenge",
  },
  {
    id: "physical-challenge",
    title: "Finish What You Trained For",
    emoji: "🏅",
    category: ["Growth", "Adventure", "Fitness"],
    difficulty: 4,
    duration: "Several weeks",
    description:
      "Choose a physical challenge worth training for, then cross the finish line knowing you earned every step.",
    objectives: [
      "Choose a challenge",
      "Train consistently",
      "Complete the event",
    ],
    reward: "The confidence only effort can build.",
    pack: "growth-challenge",
  },
  {
    id: "learn-self-defense",
    title: "Strength With Control",
    emoji: "🥋",
    category: ["Growth", "Fitness"],
    difficulty: 3,
    duration: "4-8 weeks",
    description:
      "Learn the basics of self-defense from people who know what they're doing. Confidence grows best alongside good technique.",
    objectives: [
      "Find a qualified class",
      "Attend multiple sessions",
      "Practice the fundamentals safely",
    ],
    tip: "Find a proper class rather than trying to learn this alone.",
    reward: "Confidence that doesn't need to prove itself.",
    pack: "growth-challenge",
  },
];



const packs = [
  {
    id: "nature-outdoor",
    name: "Nature & Outdoor",
    description: "Disconnect from screens and reconnect with the outside world.",
    coverEmoji: "🌲",
    questIds: allQuests.filter(q => q.pack === "nature-outdoor").map(q => q.id)
  },
  {
    id: "connection",
    name: "Connection",
    description: "Adventures designed to bring you closer to others.",
    coverEmoji: "🤝",
    questIds: allQuests.filter(q => q.pack === "connection").map(q => q.id)
  },
  {
    id: "solo",
    name: "Solo",
    description: "Learn to enjoy your own company.",
    coverEmoji: "☕",
    questIds: allQuests.filter(q => q.pack === "solo").map(q => q.id)
  },
  {
    id: "creativity",
    name: "Creativity",
    description: "Unleash your inner artist and make something new.",
    coverEmoji: "🎨",
    questIds: allQuests.filter(q => q.pack === "creativity").map(q => q.id)
  },
  {
    id: "city-explorer",
    name: "City Explorer",
    description: "Discover hidden gems in your own backyard.",
    coverEmoji: "🏛️",
    questIds: allQuests.filter(q => q.pack === "city-explorer").map(q => q.id)
  },
  {
    id: "growth-challenge",
    name: "Growth & Challenge",
    description: "Push your boundaries and build new habits.",
    coverEmoji: "🧗",
    questIds: allQuests.filter(q => q.pack === "growth-challenge").map(q => q.id)
  }
];
